Repository hapijs/boom, pull requests merged in 2019-09, with the labels that each got.

#236 Update API
  API.md
Labels: documentation

#238 Fix types: serviceUnavailable -> serverUnavailable.
  lib/index.d.ts
  test/index.ts
Labels: bug, types

#240 Fix types: Update static isBoom to be a type guard.
  lib/index.d.ts
  test/index.ts
Labels: types

#245 Fix default export. Fixes #244.
  lib/index.js
  test/index.ts
Labels: bug

#250 Remove TOC from API
  API.md
Labels: documentation

#255 Remove top header
  API.md
Labels: documentation
